1. Apakah [1,3] adalah eigen vector dari [1,−1],[6,4] ? Jika Iya, berapakah eigen value-nya?

In [3]:
import numpy as np
import matplotlib.pyplot as plt
A = np.array([[1, -1],
              [6, -4]])

A

array([[ 1, -1],
       [ 6, -4]])

In [5]:
eig_value, eig_vector = np.linalg.eig(A)


In [9]:
eig_value

array([-1., -2.])

In [10]:
eig_vector

array([[0.4472136 , 0.31622777],
       [0.89442719, 0.9486833 ]])

In [8]:
reconstruct = eig_vector @ np.diag(eig_value) @ np.linalg.inv(eig_vector)
reconstruct

array([[ 1., -1.],
       [ 6., -4.]])

[1,3] bukanlah eig value dari A