1. Buatlah Tensor di bawah ini dengan Python:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.array([[[23,50,],
            [7,12]],
            [[56,57],
            [99,43]],
            [[72,12],
            [57,12]],
            [[87,26],
            [18,84]]])
a

array([[[23, 50],
        [ 7, 12]],

       [[56, 57],
        [99, 43]],

       [[72, 12],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

2. Lakukan perkalian terhadap matrix berikut: 

In [9]:
A = np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])
B =np.array([[17],
            [12],
            [19]])
A @ B

array([[1352],
       [2334],
       [3635]])

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini

In [11]:
A.T # Transpose

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [12]:
np.linalg.det(A)

131344.0000000002

In [14]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])